/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterRequest { 
    username?: string;
    password?: string;
    first_name?: string;
    last_name?: string;
    email?: string;
    phone_number?: string;
    picture?: string;
    email_verified?: boolean;
    locale?: string;
}

